name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
   armDeploy:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - name: Azure Login
            uses: Azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Deploy Resource Group rg-githubactions
            uses: Azure/arm-deploy@v1
            with:
              scope: subscription
              subscriptionId: 2675b1a4-e6f2-49ba-b60d-653963841e47
              region: UK South
              template: ./arm-templates/resourcegroup.json
              parameters:
                location="UK West"
                resourceGroupName=rg-githubactions
              deploymentName: rg-githubactions

          - name: Deploy Storage Account
            uses: Azure/arm-deploy@v1
            id: storageAccountDeploy
            with:
              scope: resourcegroup
              resourceGroupName: rg-githubactions
              subscriptionId: 2675b1a4-e6f2-49ba-b60d-653963841e47
              template: ./arm-templates/storageaccount.json
              parameters: 
                sku=Standard_LRS
                StorageAccountName=globostg002barry
                location="UK West"
              deploymentMode: incremental
 
          - run: echo ${{ steps.storageAccountDeploy.outputs/BlobUri }}
